// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace uk.co.edgewords.webdrivernunitdemo.Test_Cases
{
    [TestFixture]
    public class FormTestTest : Utilities.TestBase
    {
        //Created using Selenium IDE
        //Now gets setup by inheriting from TestBase
        //The IDE also creates unused code for e.g. injecting JS in to the browser.
        

        [Test,Category("Smoke")]
        public void formTest()
        {
            // Test name: FormTest
            // Step # | name | target | value
            // 1 | open | /webdriver2/ | 
            
            driver.Navigate().GoToUrl("https://www.edgewordstraining.co.uk/webdriver2/");
            // 2 | setWindowSize | 822x1011 | 
            driver.Manage().Window.Size = new System.Drawing.Size(822, 1011);
            // 3 | click | css=.last span | 
            driver.FindElement(By.CssSelector(".last span")).Click();
            // 4 | click | css=li:nth-child(3) span | 
            driver.FindElement(By.CssSelector("li:nth-child(3) span")).Click();
            // 5 | click | id=textInput | 
            driver.FindElement(By.Id("textInput")).Click();
            // 6 | type | id=textInput | Steve
            driver.FindElement(By.Id("textInput")).SendKeys("Steve");
            // 7 | click | id=textArea | 
            driver.FindElement(By.Id("textArea")).Click();
            // 8 | type | id=textArea | was\nhere\n
            driver.FindElement(By.Id("textArea")).SendKeys("was\\nhere\\n");
            // 9 | click | id=checkbox | 
            driver.FindElement(By.Id("checkbox")).Click();
            // 10 | click | id=select | 
            driver.FindElement(By.Id("select")).Click();
            // 11 | select | id=select | label=Selection Two
            {
                var dropdown = driver.FindElement(By.Id("select"));
                dropdown.FindElement(By.XPath("//option[. = 'Selection Two']")).Click();
            }
            // 12 | click | id=two | 
            driver.FindElement(By.Id("two")).Click();
            // 13 | click | linkText=Submit | 
            driver.FindElement(By.LinkText("Submit")).Click();
            // 14 | click | css=tr:nth-child(2) > td:nth-child(3) | 
            driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(3)")).Click();
            // 15 | assertText | id=textInputValue | Steve
            Assert.That(driver.FindElement(By.Id("textInputValue")).Text, Is.EqualTo("Steve"));
            // 16 | click | linkText=Back to form | 
            driver.FindElement(By.LinkText("Back to form")).Click();
            // 17 | click | css=li:nth-child(1) span | 
            driver.FindElement(By.CssSelector("li:nth-child(1) span")).Click();
        }
    }
}